### PR TITLE
Know the Terrain & The Crashing Wave

### LINKED ISSUE #40: CW - The Crashing Wave
image

### LINKED ISSUE #153: SD - Know The Terrain
image

### PR DESCRIPTION
**Pull request by marcsoiferman**
Closes #40
Closes #153

### CODE REVIEW

File: server/game/game.js [hunk 1]
```diff
@@ -264,6 +264,19 @@ class Game extends EventEmitter {
     }
 
     isDuringConflict(types) {
+        if(!this.currentConflict) {
+            return false;
+        } else if(this.currentConflict && !this.currentConflict.conflictStarted) {
```
Comment (jeremylarner) [inline server/game/game.js]: I don't think this is a good idea - the engine shouldn't need to track whether the conflict has actually started or not here.

Comment (jeremylarner) [inline server/game/game.js]: I don't think this is a good idea - the engine shouldn't need to track whether the conflict has actually started or not here.

File: server/game/gamesteps/conflict/conflictflow.js [hunk 2]
```diff
@@ -97,29 +117,68 @@ class ConflictFlow extends BaseStepWithPipeline {
...
+                    }).addEventsToArray(events, this.game.getFrameworkContext(this.conflict.attackingPlayer));
+                }
+                events.push(this.game.getEvent(EventNames.Unnamed, {}, () => {
+                    this.game.queueSimpleStep(() => this.promptForCovert());
+                    this.game.queueSimpleStep(() => this.resolveCovert());
+                }));
+                this.game.openThenEventWindow(events);
+            } else {
+                this.game.addMessage('{0} has failed to initiate a conflict because they no longer have any legal attackers', this.conflict.attackingPlayer);
+                this.conflict.conflictFailedToInitiate = true;
```
Comment (jeremylarner) [inline server/game/gamesteps/conflict/conflictflow.js]: Maybe add an event cancel here?

File: server/game/gamesteps/conflict/conflictflow.js [hunk 3]
```diff
@@ -59,14 +54,39 @@ class ConflictFlow extends BaseStepWithPipeline {
...
+                    event.ringFate = this.conflict.ring.fate;
+                } else {
+                    event.cancel();
+                }
+            });
+            this.game.queueSimpleStep(() => this.payAttackerCosts());
+            this.game.queueSimpleStep(() => this.initiateConflict());
+            this.game.queueSimpleStep(() => {
+                if(this.conflict.conflictPassed || this.conflict.conflictFailedToInitiate) {
+                    event.cancel();
```
Comment (jeremylarner) [inline server/game/gamesteps/conflict/conflictflow.js]: I don't think you need both event cancels here

File: server/game/gamesteps/conflict/conflictflow.js [hunk 4]
```diff
@@ -97,29 +115,69 @@ class ConflictFlow extends BaseStepWithPipeline {
...
-        }
+        const params = {
+            conflict: this.conflict,
+            type: this.conflict.conflictType,
+            ring: this.conflict.ring,
+            attackers: this.conflict.attackers.slice(),
+            ringFate: this.conflict.ring.fate
+        };
+
+        this.game.raiseEvent(EventNames.OnConflictDeclaredBeforeProvinceReveal, params, event => {
```
Comment (jeremylarner) [inline server/game/gamesteps/conflict/conflictflow.js]: this should be:
this.game.queueThenEventWindow([this.game.getEvent(EventNames.OnConflictDeclaredBeforeProvinceReveal, params, event => {

File: server/game/gamesteps/conflict/conflictflow.js [hunk 5]
```diff
@@ -97,29 +115,69 @@ class ConflictFlow extends BaseStepWithPipeline {
...
+                        origin: this.conflict.ring,
+                        recipient: this.conflict.attackingPlayer,
+                        amount: this.conflict.ring.fate
+                    }).addEventsToArray(events, this.game.getFrameworkContext(this.conflict.attackingPlayer));
+                }
+                events.push(this.game.getEvent(EventNames.Unnamed, {}, () => {
+                    this.game.queueSimpleStep(() => this.promptForCovert());
+                    this.game.queueSimpleStep(() => this.resolveCovert());
+                }));
+                this.game.openThenEventWindow(events);
```
Comment (jeremylarner) [inline server/game/gamesteps/conflict/conflictflow.js]: I think we need to raise a Crashing Wave event here, but it seems weird to open two event windows like this in a row...
